### PR TITLE
Update Tests for log checking and fix slice marshaling bug

### LINKED ISSUE #64: [v2] Possible marshal/unmarshaling bug
I've been getting warnings from the logger I placed in the `onError` function:

`nds:loadCache setValue: datastore: cannot load field "rg" into a "models.UserAccount": multiple-valued property requires a slice field type`

I think there's an opportunity to update the tests to ensure that any logs made are expected, otherwise to fail. This may help uncover situations in which we think we're pulling from the cache but are really failing at a later step (e.g. `setValue`) and falling back to the datastore.

### PR DESCRIPTION
**Pull request by someone1**
I believe this fixes #64

### CODE REVIEW

File: nds.go [hunk 1]
```diff
@@ -54,6 +54,7 @@ func init() {
 	gob.Register(&datastore.Key{})
 	gob.Register(datastore.GeoPoint{})
 	gob.Register(&datastore.Entity{})
+	gob.Register([]interface{}{})
```
Comment (someone1) [inline nds.go]: Here's the bugfix - after adding the expected log checks to the test, the `TestGetSliceProperty` test kept failing with the following log:

`nds_test.go:164: gob: type not registered for interface: []interface {}`

It its my belief this was the proper fix for it.

**Comment by jongillham** [comment]
Great addition! Thanks!
